GET http://localhost:5000/api/facts/search?q=gun

###

GET http://localhost:5000/api/facts/youtube-video?q=testing+this

###

POST http://localhost:5000/api/facts/fact
Content-Type: application/json

{
  "title": "60k to 2.5 million defensive gun uses per year ",
  "link": "https://www.cdc.gov/violenceprevention/firearms/fastfact.html",
  "description": "The CDC refers to a study which found that guns have been used in 60k-2.5mil encounters per year"
}

###

POST http://localhost:5000/api/facts/fact
Content-Type: application/json

{
  "title": "Estimating Global Civilian HELD Firearms Numbers",
  "link": "http://www.smallarmssurvey.org/fileadmin/docs/T-Briefing-Papers/SAS-BP-Civilian-Firearms-Numbers.pdf",
  "category": "Guns",
  "description": "Has info on international gun ownership as of June 2018"
}
###

POST http://localhost:5000/api/facts/fact
Content-Type: application/json

{
  "title": "Estimating Global Civilian HELD Firearms Numbers",
  "link": "http://www.smallarmssurvey.org/fileadmin/docs/T-Briefing-Papers/SAS-BP-Civilian-Firearms-Numbers.pdf",
  "category": "Inequality",
}

###

POST http://localhost:5000/api/facts/fact
Content-Type: application/json

{
  "title": "Median net worth of households in 2013 dollars",
  "link": "https://www.pewresearch.org/fact-tank/2014/12/12/racial-wealth-gaps-great-recession/",
  "description": ""
}

###
POST http://localhost:5000/api/facts/vote?fact=789&vote=UP
Content-Type: application/json

{
  
}

###
POST http://localhost:5000/api/facts/delete-fact
Content-Type: application/json

{
  "id": "urzuPVnRt2WDvaBTcmxPTn"
}